language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: LI85zbVyHEi+95egqX9n0URvwW6X9n87Q8i1yvePZpGCuOWxRI7Lbqltv6q1cmxblqlFnKgkTFIYIdv5wU9AAEbboFbOkuV61yCzSyrOkVO5jdzPZaAUx3ywRMuNUNKQFDV5jb0V/n5+qxxgj9HAgZNJiLEUBaFm2xJEH+yyCoIDHWObKqlXuTUIuWd1reR4YSB62prD5sDl1sXZSTU0IiDW8Ati1R+3JWo5gF6QRb4VWXnGvxVXmdXegw+ndWDaEnhAcuHh0YFmAZvJaZL8MGYaHUa6gxrx3tBbW8dKR+uMEpneAlrAZpANoeGbZI+1Uyw1XZLzDxG4bA71baa3r5Mr8RmAtYKkEJm9f644bneWTeCJ26raUAdjbZ1j3jyxnmtyvonlMi5D1RNbU1pSCoPM21SN29+lBVgQLgO7eOJ3tsQbT+H6MHAWRxRfn9QrZKSN4mycqZ4Xnsp3n7Cmbs0ZgVxZCmKaMnTjDlB0yM7/tSYb7sln1U4LoDEk74Tpv12hzJ+L47DBGSJzifAlKFM1H8j+G6G7aTnk8ChVlR8BNeUEd/PA0u4XTTrEBcbQMP88ZVJUMWsf+G0lgcmaCggVTkMsL8+FlgR8MDuYcn7Pw2G3tDnHsEVe0cdmv+8hF/nBFE+3N8dOFVohvml+hN21kjP37YoZPH3xrvf8UMc=
  app: desolate-sea-45830
  on:
    repo: esokoletsky/restaurantCiDployment
    branch: feature/with-tests
 