language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: hO8DKbq9GlwWBKjo7lVvpPcvHj58oT3MsTkQ1f83abi3bqp/0E2Ce3230SszUa1pnTiCdAJFDOe0hyzMBne5aYxyKJCpCxKM3qesFHb0ar74iLTyuJ/S+nagaFa+E2gvo2vqJ5K85lCfqJ/ok5uMc0xQRtooWdP1qWJKXzopqKeAJwgNOmvyO0jC9YUgDaS0pcQmKDBcNXt4RkrghKVLJUXoeONHEJLVKwNlzqVhnCB6CPsMOab4TeDzhtZgP1zIounyeZ35Jwgs9XPYK6IVsH1zBNBg3DzitPxgSPy3i/YaEvsmZqzI0Vpg3RRiezs0odf5ZL4Mzd+v0Z6vY+iE6wm0NvGvAuqrih/Jx6Ux9AcWXg8YUvL7jPELIOZjGPxcjG1plRN0/v3sDhpAsP3yYCGR7XsaTpZ9hsnqpUr82HWhwqL3qxJ1BWcXYSe1Gu9w0FS8LURt8vvgl+c27jmveeAxJVJP0fDpID9JwOKbLJFvVrtSyKXnQX7rjTKhPR6HeJxgusJ68m6vdMcUBuVFpWRah4bq0bFWXClsa1yfz4LK3JuGLUyCF2hIIKH5cfBQFrY0QqUwD7fKCBhsHOhEMB7FywwFuoKhtqmoq7+wsNAE2fHqOKq3Aoo0WMQs6HR18t7SMOoWOZo1+Nl4WtnPEq7tQRb0tc3nD6sTshs6YKE=
  app: desolate-sea-45830
  on:
    repo: esokoletsky/restaurantCiDployment
    branch: feature/with-tests
 